maxbot:
  token: none # O token do bot que você quer ligar
  ticket: none # ID da categoria do ticket
  guild: none # ID do servidor do seu discord
  mercado-pago: # Aqui você colocará os dados do seu mercado pago
    access-token: none
    external-pos-id: none
    user-id: none

  commands: # Após a detecção do pagamento, o comando abaixo é rodado
    vip: 'darvip %s %s 30'
    cash: 'cash adicionar %s %s'
    unban: 'desbanir %s'